# Generated by Django 5.0.7 on 2024-08-03 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_scraper', '0005_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
