# Generated by Django 5.0.7 on 2024-08-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_scraper', '0007_stock_open_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
