# Generated by Django 5.0.7 on 2024-08-17 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_scraper', '0008_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
